### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by ahuth**
WIP

### CODE REVIEW

**Comment by ahuth** [comment]
@naiyt and @cantino, this PR removes some duplicate dependencies in the gem. Will be required to get the rails_4 branch back on the master branch of this fork of this gem.

**Comment by ahuth** [comment]
Also note that some changes have been brought over from HubSpot's version of the gem.

**Comment by naiyt** [comment]
Cool, LGTM. We'll want to make sure we include the Hubsot integrations when we QA Rails 4. (Not entirely sure where we're actually using this.)

**Comment by ahuth** [comment]
THanks, merging.

**Comment by ahuth** [comment]
Or not. I'm not a collaborator, and can't merge. @cantino, can you please merge?

**Comment by naiyt** [comment]
Looks like I can

**Pull request merged**
